name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
# installing dependences and executing automated tasks

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders 
              run: ls
               